version: '3.9'
services:
    # Node
    server:
        image: server
        container_name: ${SERVER_HOST}
        build: 
            context: ./
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - ./src:/src
            - server-v-node-modules:/node_modules
    
    # Nginx
    reverse-proxy:
        image: reverse-proxy
        container_name: ${REVERSE_PROXY_HOST}
        build:
            context: ./reverse-proxy
            dockerfile: Dockerfile
        env_file: .env
        restart: always
        ports:
            - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}
        volumes:
            - ./reverse-proxy/default.conf.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - server

volumes:
    server-v-node-modules:
        name: server-v-node-modules